'''
Author: CHB-learner 211430209@mail.dhu.edu.cn
Date: 2024-12-21 11:31:31
FilePath: /whynot-Django/python222_site1/python222_site1/settings.py
Description: 

项目的配置文件，项目的所有功能都需要在该文件中进行配置；
项目的配置文件，项目的所有功能都需要在该文件中进行配置；
项目的配置文件，项目的所有功能都需要在该文件中进行配置；
项目的配置文件，项目的所有功能都需要在该文件中进行配置；
项目的配置文件，项目的所有功能都需要在该文件中进行配置；


Copyright (c) 2024 by CHB-learner 211430209@mail.dhu.edu.cn, All Rights Reserved. 
'''
"""
Django settings for python222_site1 project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
#   项目的根目录        / 项目的子目录          
BASE_DIR = Path(__file__).resolve().parent.parent       # 项目的根目录


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#       项目的密钥
SECRET_KEY = 'django-insecure-!h10fgrj7hm_kp4+tsi=*!x)iwks+%x5w5050!2+7+zj@verrp'

# SECURITY WARNING: don't run with debug turned on in production!
#       项目的调试模式
DEBUG = True


#       项目的允许访问的主机
ALLOWED_HOSTS = []


# Application definition
#       项目的应用
INSTALLED_APPS = [
    'django.contrib.admin',# 管理员
    'django.contrib.auth',# 认证
    'django.contrib.contenttypes',# 内容类型
    'django.contrib.sessions',# 会话
    'django.contrib.messages',# 消息
    'django.contrib.staticfiles',# 静态文件
    'helloWorld.apps.HelloworldConfig',  # 注册helloWorld应用
]

#       项目的中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'helloWorld.mymid.md1.Md1',  # 注册自定义中间件
]

'''
SecurityMiddleware:内置的安全机制，保护用户与网站的通信安全。
SessionMiddleware:会话Session功能。
LocaleMiddleware:国际化和本地化功能。
CommonMiddleware:处理请求信息，规范化请求内容。
CsrfViewMiddleware:开启CSRF防护功能。
AuthenticationMiddleware:开启内置的用户认证系统。
MessageMiddleware:开启内置的信息提示功能。
XFrameOptionsMiddleware:防止恶意程序单击劫持。
'''

ROOT_URLCONF = 'python222_site1.urls'  # 项目的路由根目录


#       项目的模板
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',       # 模板引擎
        'DIRS': [os.path.join(BASE_DIR, 'templates'),os.path.join(BASE_DIR, 'helloWorld','templates')],      # 模板目录
        'APP_DIRS': True,       # 是否启用app模板
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'python222_site1.wsgi.application' # 项目的WSGI应用，项目部署时使用


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



#    项目的数据库
DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'db_python222',
    'USER': 'root',
    'PASSWORD': '11111111',
    'HOST': 'localhost',
    'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ # 密码验证器
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us' # 语言代码

# TIME_ZONE = 'UTC' # 时区
TIME_ZONE = 'Asia/Shanghai' # 时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# 项目的静态文件目录
STATIC_URL = 'static/'

# 项目的静态文件目录
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # 静态文件目录
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' # 默认的主键类型


# 设置媒体路由
MEDIA_URL = 'media/'

# 设置media目录的完整路径
MEDIA_ROOT = BASE_DIR / 'media'



# 设置是否在URL后面添加斜杠
# APPEND_SLASH = False
